"""Se agrego OTP a suer

Revision ID: bada4791287e
Revises: 
Create Date: 2026-06-22 11:38:09.479799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bada4791287e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('otp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('usuario', sa.Column('otp_enabled', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'otp_enabled')
    op.drop_column('usuario', 'otp_secret')
    # ### end Alembic commands ###
